# Generated by Django 6.0.7 on 2026-07-28 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhlToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('location_id', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('user_type', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ghl_tokens',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['location_id'], name='ghl_tokens_locatio_aa1963_idx'), models.Index(fields=['expires_at'], name='ghl_tokens_expires_745662_idx')],
            },
        ),
    ]
