# Generated by Django 6.0.7 on 2026-07-29 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlUser',
            fields=[
                ('ghl_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location_id', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(blank=True, max_length=60)),
                ('role_type', models.CharField(blank=True, max_length=60)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghl_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ghl_users',
                'ordering': ['name', 'ghl_id'],
                'indexes': [models.Index(fields=['location_id'], name='ghl_users_locatio_63118f_idx'), models.Index(fields=['email'], name='ghl_users_email_966012_idx')],
            },
        ),
    ]
