# Generated by Django 6.0.7 on 2026-09-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonvideo_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='import_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='import_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('slideshow', 'Slideshow')], default='text', max_length=10),
        ),
        migrations.CreateModel(
            name='SlideshowSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='slideshow_slides/')),
                ('hotspots', models.JSONField(blank=True, default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_slides', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
