# Generated by Django 6.0.7 on 2026-09-08 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_slideshow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowslide',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SlideshowSlideVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='courses.slideshowslide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_slide_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slide')},
            },
        ),
    ]
