# Generated by Django 6.0.7 on 2026-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_slideshow_required_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='import_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
