# Generated by Django 6.0.7 on 2026-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_import_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='import_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='import_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='import_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hotspots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('slideshow', 'Slideshow'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
