# Generated by Django 6.0.7 on 2026-09-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_import_error_course_import_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_visited_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson'),
        ),
    ]
