# Generated by Django 6.0.7 on 2026-08-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('agent_type', models.CharField(blank=True, max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpreadsheetSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_count', models.PositiveIntegerField(default=0)),
                ('configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spreadsheet sync state',
                'verbose_name_plural': 'Spreadsheet sync state',
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['is_active', '-start_date'], name='onboarding__is_acti_6f268d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('role', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('agent_type', models.CharField(blank=True, max_length=80)),
                ('manually_at_risk', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='onboarding.cohort')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_onboarding_agents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_onboarding_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_items', to='onboarding.checklistitemdefinition')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboardingagent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentCarrierRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='not_started', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_carrier_requirements', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_carrier_requirements', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_requirements', to='onboarding.carrier')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_requirements', to='onboarding.onboardingagent')),
            ],
            options={
                'ordering': ['carrier__sort_order', 'carrier__name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('agent_created', 'Agent created'), ('checklist_completed', 'Checklist completed'), ('checklist_uncompleted', 'Checklist uncompleted'), ('carrier_status', 'Carrier status'), ('flagged', 'Flagged'), ('unflagged', 'Unflagged'), ('comment', 'Comment'), ('owner_assigned', 'Owner assigned'), ('at_risk', 'Marked at risk')], max_length=40)),
                ('label', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_events', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='onboarding.onboardingagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_risk_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overdue_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='onboarding.requirementtemplate')),
            ],
            options={
                'verbose_name': 'Onboarding settings',
                'verbose_name_plural': 'Onboarding settings',
            },
        ),
        migrations.CreateModel(
            name='TemplateCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='onboarding.carrier')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_carriers', to='onboarding.requirementtemplate')),
            ],
            options={
                'ordering': ['carrier__sort_order', 'carrier__name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='onboarding.checklistitemdefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='onboarding.requirementtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingagent',
            index=models.Index(fields=['cohort', 'full_name'], name='onboarding__cohort__605fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingagent',
            index=models.Index(fields=['needs_sync'], name='onboarding__needs_s_5a51b4_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingagent',
            index=models.Index(fields=['owner'], name='onboarding__owner_i_b99f27_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingagent',
            index=models.Index(fields=['start_date'], name='onboarding__start_d_e5fc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentchecklistitem',
            index=models.Index(fields=['is_completed'], name='onboarding__is_comp_8c949b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentchecklistitem',
            index=models.Index(fields=['is_flagged'], name='onboarding__is_flag_8a6dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentchecklistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('definition__isnull', False)), fields=('agent', 'definition'), name='uniq_agent_checklist_definition'),
        ),
        migrations.AddIndex(
            model_name='agentcarrierrequirement',
            index=models.Index(fields=['status'], name='onboarding__status_a4ba94_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcarrierrequirement',
            index=models.Index(fields=['is_flagged'], name='onboarding__is_flag_b2b06f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentcarrierrequirement',
            unique_together={('agent', 'carrier')},
        ),
        migrations.AddIndex(
            model_name='onboardingevent',
            index=models.Index(fields=['-created_at'], name='onboarding__created_004733_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecarrier',
            unique_together={('template', 'carrier')},
        ),
        migrations.AlterUniqueTogether(
            name='templatechecklistitem',
            unique_together={('template', 'definition')},
        ),
    ]
