# Generated by Django 6.0.7 on 2026-09-02 18:00

from django.db import migrations, models


def seed_aftermath_carriers(apps, schema_editor):
    from onboarding.catalog import AFTERMATH_CARRIERS

    Carrier = apps.get_model('onboarding', 'Carrier')
    for line, sort_order, code, name in AFTERMATH_CARRIERS:
        obj, created = Carrier.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'line': line,
                'sort_order': sort_order,
                'is_active': True,
            },
        )
        if not created:
            obj.name = name
            obj.line = line
            obj.sort_order = sort_order
            obj.is_active = True
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['line', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='carrier',
            name='line',
            field=models.CharField(
                choices=[('health', 'Health'), ('life', 'Life')],
                default='life',
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_aftermath_carriers, migrations.RunPython.noop),
    ]
