# Generated by Django 6.0.7 on 2026-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingagent_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcarrierrequirement',
            name='writing_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentchecklistitem',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed'), ('approved', 'Approved')], default='incomplete', max_length=20),
        ),
    ]
